
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package name.prokofiev.accauntingservice;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.soap.SOAPBinding;

import name.prokofiev.accauntingdb.entities.Department;
import name.prokofiev.accauntingservice.jaxws.AllDepartment;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-03-30T16:13:43.681+04:00
 * Generated source version: 2.7.3
 * 
 */
public class UltimaClient {

    public static void main(String[] args) throws Exception {
        QName serviceName = new QName("http://accauntingservice.prokofiev.name/",
        		"UltimaServiceService");
        QName portName = new QName("http://accauntingservice.prokofiev.name/",
        		"UltimaServicePort");

        Service service = Service.create(serviceName);
        service.addPort(portName, SOAPBinding.SOAP12HTTP_BINDING,
                        "http://localhost:8080/accworktime/UltimaServicePort/UltimaServicePort"); 
        name.prokofiev.accauntingservice.Ultima client = service.getPort(portName, 
        		name.prokofiev.accauntingservice.Ultima.class);
        AllDepartment ad = client.getAllDepartment();
        for(Department d : ad.departmetns){
        	System.out.println(d.getName());
        }
    }

}